### ISSUE TITLE
Fail to run `azd pipeline config --provider github` and `azd pipeline config --provider azdo`

### ISSUE THREAD

**Issue by NanaXiong00** [NikiforovAll/azd-bot-service-starter#3]
**Description**
When running the `azd pipeline config --provider github` and `azd pipeline config --provider azdo` commands, the error message fails as follows:
![image](https://github.com/user-attachments/assets/119a54ef-90ff-494f-b7e6-809658c85052)
 
**Repro Steps**
1. Login in with command: `azd auth login`.
2. Run command: `azd init --template NikiforovAll/azd-bot-service-starter`.
3. Run command: `azd pipeline config --provider github` or `azd pipeline config --provider azdo`.
 
**Environment**
- OS: Windows, Codespaces.
- Azd version: azd version 1.11.0 (commit 5b92e0687e1fa96dfc8292f4b900c0c58610b6a5)
 
**Expected behavior**
`azd pipeline config --provider github` and `azd pipeline config --provider azdo` commands can be run successfully.
 
**Suggestion**
Add the dotnet installation configuration in `azure-dev.yml` file before step `Provision Infrastructure`:
- [azure-dev.yml](https://github.com/NikiforovAll/azd-bot-service-starter/blob/main/.azdo/pipelines/azure-dev.yml)

``` 
- task: UseDotNet@2
    inputs:
      packageType: 'sdk' 
      version: '9.0.x'   
```
- [azure-dev.yml](https://github.com/NikiforovAll/azd-bot-service-starter/blob/main/.github/workflows/azure-dev.yml)
```
- name: Install .NET SDK
  uses: actions/setup-dotnet@v3
  with:
    dotnet-version: '9.0.x'
```

@NikiforovAll and @hemarina for notification.
